version: '3.3'
services:
    minidlna:
        container_name: rkminidlna
        network_mode: host
        volumes:
            - '/media:/media'
        environment:
            - MINIDLNA_MEDIA_DIR=/media
            - MINIDLNA_LISTENING_IP=host
            - MINIDLNA_PORT=8200
            - MINIDLNA_FRIENDLY_NAME=rkdlna
        restart: always
        image: rkramesh/minidlna
    aria2-rpi:
        container_name: aria2
        ports:
            - '80:80'
            - '6800:6800'
        volumes:
            - '/:/data'
        restart: always
        image: rkramesh/aria2-rpi
    motioneye:
        container_name: rkeye
        ports:
            - '8765:8765'
        hostname: rkeye
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/motioneye:/etc/motioneye'
            - '/data/output:/data/output'
        restart: always
        devices:
            - /dev/video0
        image: rkramesh/motioneye
