version: '3.7'
services:
    rpi_monitor:
        devices:
            - /dev/vchiq
            - /dev/vcs
        volumes:
            - '/opt/vc:/opt/vc'
            - '/boot:/boot'
            - '/sys:/dockerhost/sys:ro'
            - '/etc:/dockerhost/etc:ro'
            - '/proc:/dockerhost/proc:ro'
            - '/usr/lib:/dockerhost/usr/lib:ro'
            - '/var/lib/rpimonitor:/var/lib/rpimonitor'
        environment:
            - LD_LIBRARY_PATH=/opt/vc/lib
        ports:
            - '8888:8888'
        container_name: rpi_monitor
        image: 'michaelmiklis/rpi-monitor:latest'
        restart: unless-stopped
    botapiplus:
        ports:
            - '8085:8081'
        container_name: bot_api
        restart: always
        volumes:
            - telegram-bot-api-data:/var/lib/telegram-bot-api
        environment:
            - TELEGRAM_API_ID=${TELEGRAM_DAEMON_API_ID}
            - TELEGRAM_API_HASH=${TELEGRAM_DAEMON_API_HASH}
        image: 'smaznet98/botapiplus:latest'
    portainer-ce:
        ports:
            - '9000:9000'
        container_name: portainer
        restart: unless-stopped
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - /'portainer_data:/data'
        image: 'portainer/portainer-ce:latest'
#    nginx:
#        container_name: rknginx
#        ports:
#            - '80:80'
#        image: 'rkramesh/nginx:v1'
#        restart: unless-stopped
    rpi-readymedia:
        container_name: readymedia
        restart: always
        volumes:
            - '/media:/data/media'
        network_mode: host
        image: rkramesh/minidlna
#    aria2-rpi:
#        container_name: aria2
#        ports:
#            - '8082:80'
#            - '6800:6800'
#        volumes:
#            - '/:/data'
#            - '/media:/media'
#        restart: always
#        image: rkramesh/aria2-rpi
    rkeye:
        container_name: rkeye
        ports:
            - '8765:8765'
        hostname: rkeye
        environment:
          - BOT_TOKEN=${BOT_TOKEN}
          - CHAT_ID=${CHAT_ID}
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/media:/media'
            - '/etc/motioneye:/etc/motioneye'
            - '/data/output:/data/output'
        restart: always
        devices:
            - /dev/video0
        image: rkramesh/motioneye:latest
    adb:
       container_name: adb
       image: rkramesh/adb
       command: >
         /bin/sh -c 'adb disconnect &&
                     adb connect 192.168.1.252 &&
                     sleep 5 &&
                     adb devices &&
                     while true; do
                       adb logcat -c && adb logcat | awk "/http:\/\/.*\?/ && !/0\$$/ && !/\)\$$/ {
                         match(\$$0, /http:\/\/[^ ]+/);
                         url = substr(\$$0, RSTART, RLENGTH);
                         title = gensub(/.*\/([^\/]+).*.m3u8.*/, \"\\1\", \"g\", url);
                         printf \"#EXTINF:0,%s\\n%s\\n\", url, url
                       }" | tee  /media/media.m3u;
                       sleep 3;
                     done'
       volumes:
            - '/media:/media'
    pyup:
       container_name: pyup
       ports:
           - '8000:8033'
       volumes:
           - '/root:/root'
           - '/media:/media'
       image: rkramesh/pyup
       restart: on-failure
    dockerbot:
      image: rkramesh/dockerbot:m3u
      container_name: dockerbot
      network_mode: host
      cap_add:
         - NET_ADMIN
      privileged: true
      restart: always
      environment:
        - API_KEY=${INFO_BOT_TOKEN}
        - ALLOWED_IDS=${CHAT_ID}
        - TELEGRAM_API_TOKEN=${INFO_BOT_TOKEN}
        - TELEGRAM_GROUP_ID=${CHAT_ID}
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - '/etc/localtime:/etc/localtime:ro'
         - '/etc/timezone:/etc/timezone:ro'
         - /media:/media
         - /proc/sysrq-trigger:/sysrq
         - '/usr/lib/android-sdk:/dockerhost/usr/lib:ro'
#    metube:
#      hostname: rktube
#      image: ghcr.io/alexta69/metube
#      container_name: rktube
#      restart: unless-stopped
#      privileged: true
#      ports:
#        - "8081:8081"
#      volumes:
#        - /media:/downloads  
#
volumes:
  telegram-bot-api-data:
