version: '3.7'
services:
    dockerevents:
        container_name: DockerEvents
        environment:
            - TELEGRAM_API_TOKEN=${INFO_BOT_TOKEN}
            - TELEGRAM_GROUP_ID=${CHAT_ID_INFO_BOT}
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - '/etc/hostname:/etc/hostname:ro'
        restart: always
        image: 'rkramesh/docker-events:est'
    minidlna:
        container_name: rkminidlna
        network_mode: host
        volumes:
            - '/media:/media'
        environment:
            - MINIDLNA_MEDIA_DIR=/media
            - MINIDLNA_LISTENING_IP=host
            - MINIDLNA_PORT=8200
            - MINIDLNA_FRIENDLY_NAME=rkdlna
        restart: always
        image: rkramesh/minidlna
    aria2-rpi:
        container_name: aria2
        ports:
            - '80:80'
            - '6800:6800'
        volumes:
            - '/:/data'
            - '/media:/media'
        restart: always
        image: rkramesh/aria2-rpi
    motioneye:
        container_name: rkeye
        ports:
            - '8765:8765'
        hostname: rkeye
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/media:/media'
            - '/etc/motioneye:/etc/motioneye'
            - '/data/output:/data/output'
        restart: always
        devices:
            - /dev/video0
        image: rkramesh/motioneye

    pyup:
            container_name: pyup
            ports:
              - '8000:8033'
            volumes:
                - '/root:/root'
                - '/media:/media'
            image: rkramesh/pyup
            restart: on-failure
    dockerbot:
      image: rkramesh/dockerbot:v1
      container_name: dockerbot
      network_mode: host
      cap_add:
         - NET_ADMIN
      privileged: true
      restart: always
      environment:
        - API_KEY=${INFO_BOT_TOKEN}
        - ALLOWED_IDS=${CHAT_ID}
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - '/etc/localtime:/etc/localtime:ro'
         - '/etc/timezone:/etc/timezone:ro'
         - /media:/media
