version: '3.8'

services:
  iphone_mount:
    container_name: iphone_mount
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${LINK_BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
    devices:
      - /dev/bus/usb
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    volumes:
      - /var/run/usbmuxd:/var/run/usbmuxd
      - ./iphone_photos:/photos
      - ./copy_album_media.sh:/copy_album_media.sh
      - ./send_album_to_telegram.sh:/send_album_to_telegram.sh
    entrypoint: /mount_iphone.sh

