version: '3.8'
services:
  sync_photo:
    container_name: sync_photo
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${LINK_BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
    devices:
      - /dev/bus/usb
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    volumes:
      - /var/run/usbmuxd:/var/run/usbmuxd
      - ./scripts:/scripts
    entrypoint: /scripts/mount_iphone.sh

